id: A9B60ED1E
title: 'The Method of Accomplishment of Ārya Avalokiteśvara: The Practice of Great
  Compassion & Mahāmudrā in Union'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:54:22.525498
  last_modified_at: 2022-03-01 02:54:22.525501
