id: A9B60ED1E
title: 'The Source of Abundant Merit: A Feast-Offering for the Secret Practice of
  the Great Compassionate One, Natural Liberation of Suffering from The Heart Essence
  of the Vast Expanse'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:54:22.529423
  last_modified_at: 2022-03-01 02:54:22.529426
