id: A9B60ED1E
title: Prayer to Avalokiteśvara
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:54:22.522831
  last_modified_at: 2022-03-01 02:54:22.522833
