id: A9B60ED1E
title: 'The Refined Essence of Compassion: A Daily SÄdhana for the Natural Liberation
  of Suffering, the Secret Practice of the Great Compassionate One'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:54:22.526695
  last_modified_at: 2022-03-01 02:54:22.526698
