id: A9B60ED1E
title: Visualization and Mantra Recitation of the Great Compassionate One
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:54:22.538469
  last_modified_at: 2022-03-01 02:54:22.538472
