id: A9B60ED1E
title: Praise of Noble Avalokiteśvara
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:54:22.521474
  last_modified_at: 2022-03-01 02:54:22.521477
