id: A9B60ED1E
title: The Visualization of the Four Goddesses of the Great Compassionate One, Natural
  Liberation of Suffering
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:54:22.535012
  last_modified_at: 2022-03-01 02:54:22.535015
