id: A9B60ED1E
title: Vajra Speech of the Prayer to Noble Avalokiteśvara from the Great Siddha Thangtong
  Gyalpo's Lifetime as Bhikṣu Padma Karpo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:54:22.537418
  last_modified_at: 2022-03-01 02:54:22.537421
