id: A9B60ED1E
title: 'Far-Reaching Benefit of Beings, Extensive as the Sky: Visualization and Mantra
  Recitation of the Great Compassionate One'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:54:22.520068
  last_modified_at: 2022-03-01 02:54:22.520071
