id: A9B60ED1E
title: 'The Sādhana of the Five Self-Arisen Noble Brothers: An Instruction in the
  Union of Generation and Completion'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:54:22.530373
  last_modified_at: 2022-03-01 02:54:22.530376
