id: A9B60ED1E
title: 'The Vision: A Prayer to Ārya Avalokiteśvara'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:54:22.533245
  last_modified_at: 2022-03-01 02:54:22.533249
